theme: minimal-mistakes-jekyll
logo: https://media.licdn.com/dms/image/C5603AQGZ88XuCfJ0AQ/profile-displayphoto-shrink_200_200/0/1659476883859?e=2147483647&v=beta&t=55H0TS23PyGQ3eLYbh2d1RIjBlyNUDKCpZEGya6txcc
title: Github page for MITDUY
