theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fduyanle&psig=AOvVaw1_VPu8gpwz3OOMbZRRdub8&ust=1717608294547000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPC04NO7woYDFQAAAAAdAAAAABAK
title: Github page for MITDUY
